"""add_medical_and_allergy_history_to_records

Revision ID: c9df3333e3bb
Revises: 8cea0260375e
Create Date: 2025-10-20 17:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9df3333e3bb'
down_revision = '8cea0260375e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('medical_history', sa.Text(), nullable=True))
    op.add_column('medical_records', sa.Column('allergy_history', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'allergy_history')
    op.drop_column('medical_records', 'medical_history')
    # ### end Alembic commands ###

